### ISSUE TITLE
Hex Regions export bug for addi with hex immediates

### ISSUE THREAD

**Issue by finesden33** [1whatleytay/saturn#15]
for example,
.text
    addi $s0, $0, 0x1234
    addi $t0, $0, 0x0c00
    addi $t0, $t0, 0x0001
    addi $t0, $t0, 0x0001
    addi $t0, $t0, 0x0001
    addi $s0, $t0, 0xffff
    addi $t1, $0, 0xffff
    addi $t1, $t1, 0xffff
    
exports to this (with HEXV3 and 32 bit little-endian configurations):

v3.0 hex words plain
20101234 20080c00 21080001 21080001 21080001 3401ffff 01018020 3401ffff 00014820 3401ffff 01214820

**Comment by 1whatleytay** [comment]
This is expected behavior. There is no such thing as `addi $s0, $t0, 0xffff` in native MIPS bitcode. The immediate for addi is signed, so a value of `0xffff` would be equivalent to `addi $s0, $t0, -1` (e.g. subtract one vs. add `0xffff`).

Saturn knows that you probably don't want to subtract here. Instead, it will generate two instructions (a load immediate equivalent and an `addi`) so your intent is expressed properly. That's why multiple instructions are emitted here. You can see the exact instructions it emitted by hitting File -> Assemble Elf.

I'll leave this issue open for a bit longer in case you have any questions.

**Comment by SallyZhijing** [comment]
![image](https://github.com/1whatleytay/saturn/assets/127266489/d4e9fdc9-22b2-4b5c-83c9-7c975a662c57) 
This is the version I was using, and I did File->Export Hex Regions with default settings, it creates an empty folder with nothing in it: ![image](https://github.com/1whatleytay/saturn/assets/127266489/aebac8e9-7c1c-457c-8ab4-151c9fd91e8c)
but when I check the CONTINUOUS EXPORT, then it can create the file I want but with no folder.

**Comment by 1whatleytay** [comment]
This should be fixed in v0.1.8 👍

**Comment by 1whatleytay** [comment]
Going to close this with the release of v0.1.8.
